/**
 * Tool Registry — compile-time source of truth
 * New tools: add a ToolMeta entry, add messages keys, implement component, wire slug branch
 */

import { ToolMeta } from './types';

export const tools: ToolMeta[] = [
  {
    id: 'ladder',
    slug: 'ladder',
    category: 'random',
    icon: 'ListTree',
    accent: 'coral',
    status: 'live',
    addedAt: '2026-06-29',
    order: 80,
    keywords: ['사다리', '사다리타기', 'ladder', 'ghost leg', '추첨', '제비뽑기', '아미다쿠지', 'amidakuji'],
  },
  {
    id: 'qna-a-day',
    slug: 'qna-a-day',
    category: 'mindset',
    icon: 'NotebookPen',
    accent: 'grape',
    status: 'live',
    addedAt: '2026-06-30',
    order: 170,
    keywords: ['1일1질문', '하루한질문', '365질문', '질문일기', '자기성찰', '일기', '저널', 'q&a a day', 'daily question', 'journal', 'self reflection', 'one question a day'],
  },
  {
    id: 'new-word',
    slug: 'new-word',
    category: 'text',
    icon: 'BookA',
    accent: 'mint',
    status: 'live',
    addedAt: '2026-07-01',
    order: 140,
    keywords: ['신조어', '유행어', 'MZ', '밈', '용어', '용어사전', '트렌드', '바이브코딩', '바이브 코딩', '루프엔지니어링', '갓생', '억까', '새로운 말', 'new word', 'slang', 'glossary', 'terms', 'vibe coding', 'trend', 'buzzword'],
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    category: 'dev',
    icon: 'Link',
    accent: 'grape',
    status: 'live',
    addedAt: '2026-07-01',
    order: 120,
    keywords: [
      'URL', '인코딩', '디코딩', 'encode', 'decode', '%20', 'percent',
      'query', 'parameter', '쿼리', '매개변수', 'EUC-KR', 'euckr', 'CP949',
      '한글', 'UTF-8', 'charset', '개발', 'developer', 'tool'
    ],
  },
  {
    id: 'cron-parser',
    slug: 'cron-parser',
    category: 'dev',
    icon: 'Clock',
    accent: 'rose',
    status: 'live',
    addedAt: '2026-07-10',
    order: 125,
    keywords: [
      'cron', 'schedule', 'job', 'timezone', 'next-run', 'crontab',
      '크론', '크론표현식', '스케줄', '일정', '예약', '시간대', '작업',
      'unix', 'linux', '자동화', 'automation', 'developer', 'devops'
    ],
  },
  {
    id: 'rankings',
    slug: 'rankings',
    category: 'news',
    icon: 'Trophy',
    accent: 'rose',
    status: 'live',
    addedAt: '2026-07-02',
    order: 150,
    keywords: [
      '별별랭킹', '별별', '랭킹', '순위', '영화', '음식', '여행', '게임', '음악', '책', '앱',
      'rankings', 'top', 'best', 'curator', 'movies', 'restaurants', 'travel', 'games', 'music'
    ],
  },
  {
    id: 'bookmarks',
    slug: 'bookmarks',
    category: 'mindset',
    icon: 'Bookmark',
    accent: 'sky',
    status: 'live',
    addedAt: '2026-07-02',
    order: 180,
    keywords: ['즐겨찾기','북마크','링크','모음','자료','큐레이션','리소스','하네스','엔지니어링','프런트엔드','디자인','개발','전자정부','표준프레임워크','egovframe','bookmarks','links','directory','resources','curated','dev','tools'],
  },
  {
    id: 'speed-quiz',
    slug: 'speed-quiz',
    category: 'fun',
    icon: 'Zap',
    accent: 'sun',
    status: 'live',
    addedAt: '2026-07-02',
    order: 90,
    keywords: ['스피드퀴즈','제시어','파티게임','캐치마인드','게임','속담','영화','음악','단어','대사','캐릭터','배우','용어','단어게임','교실','학교','팀게임','진행자','speed quiz','prompt words','party game','charades','quiz','word game','classroom','game show','presenter','movies','k-pop','celebrities','keyword','hint'],
  },
  {
    id: 'age-calculator',
    slug: 'age-calculator',
    category: 'calculator',
    icon: 'Cake',
    accent: 'mint',
    status: 'live',
    addedAt: '2026-07-03',
    order: 30,
    keywords: ['나이','나이 계산','나이 계산기','만 나이','연 나이','세는 나이','생년월일','생일','띠','별자리','요일','살아온 날','age','age calculator','how old','birthday','zodiac','star sign','manNai','korean age'],
  },
  {
    id: 'lunar-converter',
    slug: 'lunar-converter',
    category: 'converter',
    icon: 'CalendarSync',
    accent: 'grape',
    status: 'live',
    addedAt: '2026-07-03',
    order: 50,
    keywords: ['음력','양력','음력변환','양력변환','음력달력','간지','갑자','띠','윤달','설날','생일 음력','음양력변환','달력','korean lunar','lunar calendar','solar calendar','lunar converter','sexagenary','zodiac','leap month','korean calendar','date conversion','gapja','干支'],
  },
  {
    id: 'qr-code',
    slug: 'qr-code',
    category: 'converter',
    icon: 'QrCode',
    accent: 'sky',
    status: 'live',
    addedAt: '2026-07-03',
    order: 20,
    keywords: [
      'QR', 'QR코드', 'QR코드생성', '큐알코드', 'QR generator', 'QR code',
      'Wi-Fi', 'vCard', 'URL', '이메일', '문자', 'email', 'SMS',
      '변환', 'converter', 'scan', '스캔'
    ],
  },
  {
    id: 'transparent-background',
    slug: 'transparent-background',
    category: 'converter',
    icon: 'Eraser',
    accent: 'sky',
    status: 'live',
    addedAt: '2026-07-04',
    order: 130,
    keywords: ['배경제거', '투명', '배경투명', '로컬', 'remove background', 'transparent', 'single-color', 'local', 'privacy'],
  },
  {
    id: 'dev-people',
    slug: 'dev-people',
    category: 'mindset',
    icon: 'Users',
    accent: 'sky',
    status: 'live',
    addedAt: '2026-07-04',
    order: 190,
    keywords: [
      '개발인물','개발인물사전','개발자','프로그래머','컴퓨터과학','인물','전기','biography',
      '제프리힌턴','로버트마틴','에리히감마','리처드스톨먼','제임스고슬링','브렌던아이크','리누스토발즈',
      '귀도반로섐','마틴파울러','켄트벡','얀르쿤','안드레이카파시','조코딩',
      'Geoffrey Hinton','Robert Martin','Erich Gamma','Richard Stallman','James Gosling','Brendan Eich','Linus Torvalds',
      'Guido van Rossum','Martin Fowler','Kent Beck','Yann LeCun','Andrej Karpathy',
      'Java','Python','JavaScript','C','Linux','Git','AI','Deep Learning','Clean Code','Architecture','TDD'
    ],
  },
  {
    id: 'roulette',
    slug: 'roulette',
    category: 'random',
    icon: 'RotateCcw',
    accent: 'rose',
    status: 'live',
    addedAt: '2026-07-04',
    order: 70,
    keywords: ['룰렛', '랜덤', '추첨', '선택', '결정', '돌림판', '뽑기', 'roulette', 'random', 'spin', 'decision', 'picker', 'wheel', 'lucky draw'],
  },
  {
    id: 'lotto-generator',
    slug: 'lotto-generator',
    category: 'random',
    icon: 'Dices',
    accent: 'sun',
    status: 'live',
    addedAt: '2026-07-20',
    order: 75,
    keywords: ['로또', '로또번호', '로또생성기', '번호생성', '추첨', '공정', '난수', 'lotto', 'lottery', 'number generator', 'random', 'fair draw'],
  },
  {
    id: 'restaurant-map',
    slug: 'restaurant-map',
    category: 'fun',
    icon: 'MapPin',
    accent: 'rose',
    status: 'live',
    addedAt: '2026-07-04',
    order: 160,
    keywords: ['맛집', '맛집리스트', '맛집지도', '카페', '라면', '족발', '참치', '음식', '추천', '지도', 'restaurant', 'map', 'food', 'cafe', 'ramen', 'tuna', 'local favorite', 'curator', 'dining', 'lunch', 'dinner'],
  },
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    category: 'dev',
    icon: 'Braces',
    accent: 'sky',
    status: 'live',
    addedAt: '2026-07-04',
    order: 100,
    keywords: ['JSON', '포맷', '검증', '정렬', '개발', '도구', 'URL', 'formatter', 'validator', 'minify', 'prettify'],
  },
  {
    id: 'character-counter',
    slug: 'character-counter',
    category: 'text',
    icon: 'Type',
    accent: 'mint',
    status: 'live',
    addedAt: '2026-07-04',
    order: 10,
    keywords: [
      '글자', '글자수', '글자세기', '단어', '단어수', '문장', '문단', '바이트',
      'character counter', 'word count', 'text metrics', 'character limit',
      'twitter limit', 'meta description', 'readability', 'reading time'
    ],
  },
  {
    id: 'find-replace',
    slug: 'find-replace',
    category: 'text',
    icon: 'Replace',
    accent: 'grape',
    status: 'live',
    addedAt: '2026-07-07',
    order: 15,
    keywords: [
      '찾아바꾸기', '문장바꾸기', '단어바꾸기', '일괄치환', '치환', '바꾸기',
      '정규식', '대소문자', '전체단어', '규칙', '규칙스택',
      'find and replace', 'replace all', 'bulk replace', 'text replace',
      'regex', 'substitute', 'multi-rule', 'literal', 'capture group'
    ],
  },
  {
    id: 'base64-encoder',
    slug: 'base64-encoder',
    category: 'dev',
    icon: 'Binary',
    accent: 'coral',
    status: 'live',
    addedAt: '2026-07-04',
    order: 110,
    keywords: ['base64', '인코딩', '디코딩', 'encode', 'decode', '변환', 'encoding', '파일', '텍스트', 'UTF-8', 'base64 converter', 'encoder', 'decoder'],
  },
  {
    id: 'my-ip',
    slug: 'my-ip',
    category: 'dev',
    icon: 'Globe',
    accent: 'rose',
    status: 'live',
    addedAt: '2026-07-04',
    order: 60,
    keywords: ['아이피','IP','공개IP','public IP','IPv4','IPv6','나의IP','내IP','IP찾기','IP주소','네트워크','network address','isp','my ip address','what is my ip'],
  },
  {
    id: 'unit-converter',
    slug: 'unit-converter',
    category: 'converter',
    icon: 'Ruler',
    accent: 'sky',
    status: 'live',
    addedAt: '2026-07-04',
    order: 40,
    keywords: ['단위변환', '길이', '무게', '온도', '시간', '변환', 'unit', 'conversion', 'length', 'weight', 'temperature', 'time', 'meter', 'kilogram', 'celsius', 'converter'],
  },
  {
    id: 'knitting-gauge',
    slug: 'knitting-gauge',
    category: 'calculator',
    icon: 'Ruler',
    accent: 'sun',
    status: 'live',
    addedAt: '2026-07-05',
    order: 200,
    keywords: [
      '뜨개질', '게이지', '코수', '단수', '대바늘', '코바늘', '니트', '스웨치',
      '패턴환산', '크로셰', '뜨개질계산', '코밀도', '단밀도',
      'knitting', 'gauge', 'stitches', 'rows', 'swatch', 'cast on',
      'crochet', 'pattern', 'rescale', 'finished size', 'yarn'
    ],
  },
  {
    id: 'howto',
    slug: 'howto',
    category: 'dev',
    icon: 'BookOpen',
    accent: 'sky',
    status: 'live',
    order: 31,
    addedAt: '2026-07-06',
    keywords: ['하우투', '가이드', '설치', '설정', 'how to', 'howto', 'guide', 'tutorial', '클로드 코드', 'claude code', '토큰 발급', 'api token', 'mermaid', '다이어그램', '코드블록', 'markdown', '문서', '매뉴얼', 'setup'],
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    category: 'dev',
    icon: 'KeyRound',
    accent: 'sun',
    status: 'live',
    addedAt: '2026-07-11',
    order: 105,
    keywords: ['JWT', '디코더', '토큰', '분석', '검증', '서명', '개발', 'decoder', 'verify', 'token', 'payload', 'claims', 'security', 'JSON Web Token', 'cryptography'],
  },
  {
    id: 'cheer',
    slug: 'cheer',
    category: 'fun',
    icon: 'Megaphone',
    accent: 'coral',
    status: 'live',
    addedAt: '2026-07-20',
    order: 185,
    keywords: ['응원', '응원문구', '응원도구', '전광판', 'LED', '콘서트', '경기장', '배너', '슬로건', 'cheer', 'banner', 'marquee', 'LED sign', 'concert', 'stadium', 'fan', 'chant', 'slogan', 'scrolling text', 'fun'],
  },
];

/** Get all live tools for static generation */
export function getLiveTools() {
  return tools.filter((tool) => tool.status === 'live');
}

/** Get tool by slug */
export function getToolBySlug(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
